export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODOS_INIT = 'FETCH_TODOS_INIT';
export const FETCH_TODOS_START = 'FETCH_TODOS_START';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAIL = 'FETCH_TODOS_FAIL';

export const CREATE_TODO = 'CREATE_TODO';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
export const CREATE_TODO_FAIL = 'CREATE_TODO_FAIL'
